/* soapsclwsProxy.h
   Generated by gSOAP 2.7.11 from ../include/sclwsWS.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapsclwsProxy_H
#define soapsclwsProxy_H
#include "soapH.h"
extern SOAP_NMAC struct Namespace soap_namespaces[];
class sclws
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'sclws' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	sclws() { soap = soap_new(); if (soap) soap->namespaces = soap_namespaces; endpoint = "http://jmmc.fr:8079"; };
	/// Destructor frees deserialized data and soap engine context
	virtual ~sclws() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetServerStatusSearchCal' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetServerStatusSearchCal(char **status) { return soap ? soap_call_ns__GetServerStatusSearchCal(soap, endpoint, NULL, status) : SOAP_EOM; };
	/// Invoke 'GetCalOpenSession' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetCalOpenSession(char **jobId) { return soap ? soap_call_ns__GetCalOpenSession(soap, endpoint, NULL, jobId) : SOAP_EOM; };
	/// Invoke 'GetCalSearchCal' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetCalSearchCal(char *jobId, char *query, char **voTable) { return soap ? soap_call_ns__GetCalSearchCal(soap, endpoint, NULL, jobId, query, voTable) : SOAP_EOM; };
	/// Invoke 'GetCalQueryStatus' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetCalQueryStatus(char *jobId, char **status) { return soap ? soap_call_ns__GetCalQueryStatus(soap, endpoint, NULL, jobId, status) : SOAP_EOM; };
	/// Invoke 'GetCalCancelSession' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetCalCancelSession(char *jobId, bool *isOK) { return soap ? soap_call_ns__GetCalCancelSession(soap, endpoint, NULL, jobId, isOK) : SOAP_EOM; };
	/// Invoke 'GetStarSearchCal' of service 'sclws' and return error code (or SOAP_OK)
	virtual int ns__GetStarSearchCal(char *query, char **votable) { return soap ? soap_call_ns__GetStarSearchCal(soap, endpoint, NULL, query, votable) : SOAP_EOM; };
};
#endif
